// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUE4JjXVTRYksaqROHk2YeiOgfizS5ZXg',
    appId: '1:125901481280:web:7208c9c3baacc9426406a5',
    messagingSenderId: '125901481280',
    projectId: 'midternexam',
    authDomain: 'midternexam.firebaseapp.com',
    storageBucket: 'midternexam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9Iia9U1-rxy7DJHt-kP8suznl1d-sYs',
    appId: '1:125901481280:android:57f9b122f365ea086406a5',
    messagingSenderId: '125901481280',
    projectId: 'midternexam',
    storageBucket: 'midternexam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucfyLLq21BUr9GAYLKwIYCbDPtW7F5f4',
    appId: '1:125901481280:ios:a958f987b4083b696406a5',
    messagingSenderId: '125901481280',
    projectId: 'midternexam',
    storageBucket: 'midternexam.appspot.com',
    iosBundleId: 'com.example.midternExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucfyLLq21BUr9GAYLKwIYCbDPtW7F5f4',
    appId: '1:125901481280:ios:a958f987b4083b696406a5',
    messagingSenderId: '125901481280',
    projectId: 'midternexam',
    storageBucket: 'midternexam.appspot.com',
    iosBundleId: 'com.example.midternExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUE4JjXVTRYksaqROHk2YeiOgfizS5ZXg',
    appId: '1:125901481280:web:8564d14d0a700ea76406a5',
    messagingSenderId: '125901481280',
    projectId: 'midternexam',
    authDomain: 'midternexam.firebaseapp.com',
    storageBucket: 'midternexam.appspot.com',
  );
}
